### ISSUE TITLE
Comma Formatting to the Numbers Displaying to the User

### ISSUE THREAD

**Issue by gitpancake** [ConorLeckey/Tileman-Mode#26]
Noticed that there is no comma formatting on the numbers that display to the users.

This may be nice to have. Have posted image below, and have added the code to do this in a separate branch, only I cannot create a Pull Request! 

![here](https://i.imgur.com/TAoit8s.png)

Keen to hear thoughts / feedback on this.

**Comment by sram1337** [comment]
Thanks for the suggestion and implementation! One concern I have is that we
would need to account for the added width from the comma in the string to
prevent wrapping the text to a new line.

**Comment by gitpancake** [comment]
@sram1337  ah, really good concern. I hadn't factored this in. 

I can update the code to stretch out that box slightly. What do you think?

**Comment by sram1337** [comment]
Yes sounds good!

**Comment by ConorLeckey** [comment]
Love this idea :)

**Comment by gitpancake** [comment]
Just having a look through and came across this in `TileInfoOverlay.java`

```
panelComponent.setPreferredSize(new Dimension(
                getLongestStringWidth(STRINGS, graphics)
                        + getLongestStringWidth(new String[] {unlockedTiles, unspentTiles}, graphics),
                0));
```

This should set the width based on the strings, and seeing as the strings now include the commas, then the panel should stretch to fit the updated strings - unless this is overridden elsewhere?

**Comment by ConorLeckey** [comment]
This has been added in the latest update :)
