### ISSUE TITLE
Tutorial island tiles are marked sometimes

### ISSUE THREAD

**Issue by Alicecomma** [ConorLeckey/Tileman-Mode#28]
- The surface of the island is marked when you toggle "Auto-mark tiles" on, but not when you toggle it off or when it's already on/off

- The underground section is marked with "Auto-mark tiles" on

**Comment by sram1337** [comment]
Thanks for filing this @Alicecomma !
Are you in the Discord? https://discord.gg/R5mMmuE

**Comment by Alicecomma** [comment]
Yes, "Alistaire#2135"

**Comment by jzips** [comment]
Hi there, not sure if this is a related issue but the plugin will not mark tiles as I walk on tutorial island. jzips9686 on discord and I will attach a video here that hopefully provides enough information. Thank you!

https://user-images.githubusercontent.com/130255182/230745788-b1e8cde5-fcd8-4c7c-bcd2-ecd187237988.mp4

**Comment by sram1337** [comment]
@jzips yes this is intended. We intentionally made it so you can't mark tiles on Tutorial island.

The Tileman rules most people follow do not require you to mark tiles on tutorial island. Too many people were accidentally marking tiles, leaving the island, and then had no way to go back and unmark them, so we disabled it.

**Comment by jzips** [comment]
Ah okay, great to know. Thank you sram!
