### ISSUE TITLE
How to backup tiles?

### ISSUE THREAD

**Issue by oscar-o-oneill** [ConorLeckey/Tileman-Mode#33]
Hey @ConorLeckey, awesome work on this plug-in. Just wondering if there is anyway to back up my tiles? Or move them to another computer? I just don't want to lose any progress. Thanks!!

**Comment by sram1337** [comment]
Hi @oscar-o-oneill. Tile data is stored in Runelite's `settings.properties` file. For most folks this is stored in C:\Users\<Your Profile Name>\.runelite

If you are logged into the Runelite client (not Runescape but the Runelite client itself), your settings.properties file is automatically saved in the cloud - logging in on another computer should give you access to your tiles.

**Comment by oscar-o-oneill** [comment]
Hey @ConorLeckey thanks a lot for your response here. I'll see about backing it up. Thank you and great work on this plug-in!

**Comment by oscar-o-oneill** [comment]
Hey @sram1337 thanks a lot for your response here. I'll see about backing it up. Thank you!

Also love your vids on YouTube!! Love the series you uploaded there.

**Comment by oscar-o-oneill** [comment]
PS is there any risk of the tiles getting lost? Or corrupted? Or is it 10000% safe?

**Comment by sram1337** [comment]
Nothing is 100% safe, so I would back them up.

I personally play not logged to Runelite and backup my entire .Runelite folder to OneDrive.

**Comment by oscar-o-oneill** [comment]
For sure. Thanks for sharing your workflow. I agree nothing is fully safe unless you have multiple backups... And even then you could still lose it all.

Not a big deal for someone like me, but that would be catastrophic for someone like Settled who might be putting in thousands of hours into this plugin!

Also @sram1337 congrats for starting this new OSRS trend. Cool to see Settled doing it now too.

**Comment by sram1337** [comment]
For sure. And thanks - I'm so glad folks are enjoying it!
