### ISSUE TITLE
Negative Tiles after clicking Import

### ISSUE THREAD

**Issue by LittleVinne** [ConorLeckey/Tileman-Mode#39]
I'm not sure if this is a known issue, but, I couldn't find it anywhere else online. After installing Tileman mode and clicking on the import ground markers button without realizing fully what it would do. I now have negative tiles and can't seem to reset them. I've clicked reset on both the tileman mode settings and the ground marker settings, but this doesn't reset any marked tiles. I've deleted the runelite.settings file from the runelite folder, and ive uninstalled/reinstalled whilst deleting the entire runelite folder. 

Is this a bug or known issue?

Thanks

**Comment by armin218** [comment]
same issue

**Comment by ConorLeckey** [comment]
Hi, sorry if it wasn't stated clear enough. Clicking the import button ports all your current tiles from the ground marker plugin. 

So if you used it to mark tiles previously, say 100 tiles, then imported them to the tileman plugin, you would have an additional 100 tiles marked. This is likely why your tiles became negative. 

Stated above the button here as a warning. Did you make a backup before importing? If so it should be easily reverted :) 

![image](https://github.com/ConorLeckey/Tileman-Mode/assets/32102255/b1cfe5f7-3952-49e3-8750-9838aea329e9)

**Comment by ConorLeckey** [comment]
Closing, as seems like functionality is working as stated.
